services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

jobs:
  include:
    - stage: coditsu
      language: ruby
      rvm: 2.6.5
      before_install:
        - gem update --system
        - gem install bundler
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - coditsu
